name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Semantic Release
        id: semanticPreRelease
        uses: dkhunt27/semantic-release-action@v2.8.0-beta
        with:
          semantic_version: 18
          dry_run: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotate release
        uses: dkhunt27/action-annotations@beta
        with:
          type: notice
          msg: Released ${{ needs.version.outputs.publishVersion }}
